############################################################
# PATCH PREIS — REMPLACER UNIQUEMENT scripts/02_scrape_insp.R
# Version compatible R ancien : PAS de raw string r"(...)"
############################################################

BASE_DIR <- "D:/PREIS_Ebola_DRC_Sitrep_FV_12.06.26"
TARGET_FILE <- file.path(BASE_DIR, "scripts", "02_scrape_insp.R")
SCRIPTS_DIR <- file.path(BASE_DIR, "scripts")

if (!dir.exists(SCRIPTS_DIR)) {
  dir.create(SCRIPTS_DIR, recursive = TRUE, showWarnings = FALSE)
}

if (file.exists(TARGET_FILE)) {
  BACKUP_FILE <- file.path(
    SCRIPTS_DIR,
    paste0("02_scrape_insp_BACKUP_", format(Sys.time(), "%Y%m%d_%H%M%S"), ".R")
  )
  ok_backup <- file.copy(TARGET_FILE, BACKUP_FILE, overwrite = TRUE)
  if (!isTRUE(ok_backup)) stop("Backup failed. Replacement stopped.")
  cat("Backup created:", BACKUP_FILE, "\n")
} else {
  BACKUP_FILE <- NA_character_
  cat("No existing 02_scrape_insp.R found. A new file will be created.\n")
}

NEW_LINES <- c(
  "############################################################",
  "# 02_scrape_insp.R — PREIS EBOLA DRC",
  "# Scraping INSP + résolution PDF + registre robuste",
  "############################################################",
  "",
  "# ============================================================",
  "# 1) RÉSOUDRE L'URL PDF EMBARQUÉE DANS UNE PAGE SITREP",
  "# ============================================================",
  "",
  "resolve_pdf_url <- function(post_url) {",
  "",
  "  resp <- get_with_retry(post_url, timeout_sec = 90, max_try = 3)",
  "  if (is.null(resp)) return(NA_character_)",
  "",
  "  html_txt <- httr::content(resp, \"text\", encoding = \"UTF-8\")",
  "",
  "  direct <- stringr::str_extract(",
  "    html_txt,",
  "    \"https://insp\\\\.cd/wp-content/uploads/[^\\\"'\\\\s]+\\\\.pdf\"",
  "  )",
  "",
  "  if (!is.na(direct)) return(direct)",
  "",
  "  b64 <- stringr::str_match(",
  "    html_txt,",
  "    \"pdfemb-data=([A-Za-z0-9+/=]+)\"",
  "  )[, 2]",
  "",
  "  if (!is.na(b64)) {",
  "",
  "    decoded <- tryCatch(",
  "      rawToChar(base64enc::base64decode(b64)),",
  "      error = function(e) NA_character_",
  "    )",
  "",
  "    if (!is.na(decoded)) {",
  "",
  "      url <- stringr::str_match(",
  "        decoded,",
  "        '\"url\"\\\\s*:\\\\s*\"([^\"]+\\\\.pdf)\"'",
  "      )[, 2]",
  "",
  "      if (!is.na(url)) {",
  "        url <- stringr::str_replace_all(url, \"\\\\\\\\/\", \"/\")",
  "        url <- stringr::str_replace_all(url, \"\\\\\\\\u00b0\", \"°\")",
  "        url <- stringr::str_replace_all(url, \"\\\\\\\\u[0-9a-fA-F]{4}\", \"\")",
  "        return(url)",
  "      }",
  "    }",
  "  }",
  "",
  "  NA_character_",
  "}",
  "",
  "",
  "# ============================================================",
  "# 2) SCRAPER LES PAGES CATÉGORIE INSP",
  "# ============================================================",
  "",
  "scrape_insp_sitrep_list <- function(",
  "    category_url = INSP_CATEGORY_PAGE,",
  "    max_pages    = INSP_MAX_PAGES",
  ") {",
  "",
  "  cat(\">> Scraping category pages:\", category_url, \"\\n\")",
  "",
  "  all_posts <- list()",
  "",
  "  for (pg in seq_len(max_pages)) {",
  "",
  "    page_url <- if (pg == 1) {",
  "      category_url",
  "    } else {",
  "      paste0(category_url, \"page/\", pg, \"/\")",
  "    }",
  "",
  "    resp <- get_with_retry(page_url, timeout_sec = 90, max_try = 4)",
  "",
  "    if (is.null(resp)) {",
  "      if (pg == 1) {",
  "        cat(\"   ERROR: cannot reach category page after retries\\n\")",
  "      }",
  "      break",
  "    }",
  "",
  "    page_html <- rvest::read_html(",
  "      httr::content(resp, \"text\", encoding = \"UTF-8\")",
  "    )",
  "",
  "    links <- page_html %>%",
  "      rvest::html_nodes(\"a\") %>%",
  "      rvest::html_attr(\"href\")",
  "",
  "    texts <- page_html %>%",
  "      rvest::html_nodes(\"a\") %>%",
  "      rvest::html_text(trim = TRUE)",
  "",
  "    post_df <- tibble::tibble(",
  "      post_url  = links,",
  "      post_text = texts",
  "    ) %>%",
  "      dplyr::filter(",
  "        !is.na(post_url),",
  "        stringr::str_detect(post_url, \"sitrep-n\\\\d+-mvb\")",
  "      ) %>%",
  "      dplyr::distinct(post_url, .keep_all = TRUE)",
  "",
  "    if (nrow(post_df) == 0) break",
  "",
  "    all_posts[[pg]] <- post_df",
  "",
  "    cat(\"   Page\", pg, \":\", nrow(post_df), \"posts\\n\")",
  "  }",
  "",
  "  posts <- dplyr::bind_rows(all_posts) %>%",
  "    dplyr::distinct(post_url, .keep_all = TRUE)",
  "",
  "  if (nrow(posts) == 0) {",
  "    cat(\"   No 2026 MVB SitRep posts found.\\n\")",
  "    return(tibble::tibble())",
  "  }",
  "",
  "  posts <- posts %>%",
  "    dplyr::mutate(",
  "      sitrep_no = suppressWarnings(as.integer(",
  "        stringr::str_match(post_url, \"sitrep-n(\\\\d+)-mvb\")[, 2]",
  "      )),",
  "      date_raw = stringr::str_match(",
  "        post_url,",
  "        \"mvb_(\\\\d{2}-\\\\d{2}-\\\\d{4})\"",
  "      )[, 2],",
  "      epidemic = EPIDEMIC_LABEL",
  "    ) %>%",
  "    dplyr::filter(!is.na(sitrep_no)) %>%",
  "    dplyr::distinct(sitrep_no, .keep_all = TRUE) %>%",
  "    dplyr::arrange(dplyr::desc(sitrep_no))",
  "",
  "  cat(\"   Found\", nrow(posts), \"unique SitRep posts\\n\")",
  "  cat(\"   SitRep numbers:\", paste(sort(posts$sitrep_no), collapse = \", \"), \"\\n\")",
  "",
  "  cat(\"   Resolving embedded PDF URLs...\\n\")",
  "",
  "  posts$pdf_url <- purrr::map_chr(posts$post_url, resolve_pdf_url)",
  "",
  "  posts <- posts %>%",
  "    dplyr::filter(!is.na(pdf_url)) %>%",
  "    dplyr::mutate(",
  "      link_text   = paste0(\"SitRep N\", sitrep_no, \" MVB \", date_raw),",
  "      year_in_url = 2026L,",
  "      source_page = post_url,",
  "      scraped_at  = as.character(Sys.time())",
  "    )",
  "",
  "  cat(\"   Resolved\", nrow(posts), \"PDF URLs\\n\")",
  "",
  "  posts",
  "}",
  "",
  "",
  "# ============================================================",
  "# 3) NORMALISER LES TYPES DU REGISTRE",
  "# ============================================================",
  "",
  "normalize_registry_types <- function(df) {",
  "",
  "  empty <- tibble::tibble(",
  "    sitrep_no    = integer(),",
  "    pdf_url      = character(),",
  "    date_raw     = character(),",
  "    link_text    = character(),",
  "    year_in_url  = integer(),",
  "    source_page  = character(),",
  "    epidemic     = character(),",
  "    scraped_at   = character(),",
  "    downloaded   = logical(),",
  "    extracted    = logical(),",
  "    analysed     = logical(),",
  "    local_pdf    = character(),",
  "    first_seen   = character(),",
  "    last_updated = character()",
  "  )",
  "",
  "  if (is.null(df) || nrow(df) == 0) {",
  "    return(empty)",
  "  }",
  "",
  "  for (col in names(empty)) {",
  "    if (!col %in% names(df)) {",
  "      df[[col]] <- NA",
  "    }",
  "  }",
  "",
  "  df <- df %>%",
  "    dplyr::mutate(",
  "      sitrep_no   = suppressWarnings(as.integer(sitrep_no)),",
  "      year_in_url = suppressWarnings(as.integer(year_in_url)),",
  "",
  "      pdf_url     = as.character(pdf_url),",
  "      date_raw    = as.character(date_raw),",
  "      link_text   = as.character(link_text),",
  "      source_page = as.character(source_page),",
  "      epidemic    = as.character(epidemic),",
  "      local_pdf   = as.character(local_pdf),",
  "",
  "      scraped_at   = as.character(scraped_at),",
  "      first_seen   = as.character(first_seen),",
  "      last_updated = as.character(last_updated),",
  "",
  "      downloaded = dplyr::case_when(",
  "        is.na(downloaded) ~ FALSE,",
  "        as.character(downloaded) %in% c(\"TRUE\", \"true\", \"1\", \"Yes\", \"yes\") ~ TRUE,",
  "        TRUE ~ FALSE",
  "      ),",
  "      extracted = dplyr::case_when(",
  "        is.na(extracted) ~ FALSE,",
  "        as.character(extracted) %in% c(\"TRUE\", \"true\", \"1\", \"Yes\", \"yes\") ~ TRUE,",
  "        TRUE ~ FALSE",
  "      ),",
  "      analysed = dplyr::case_when(",
  "        is.na(analysed) ~ FALSE,",
  "        as.character(analysed) %in% c(\"TRUE\", \"true\", \"1\", \"Yes\", \"yes\") ~ TRUE,",
  "        TRUE ~ FALSE",
  "      )",
  "    ) %>%",
  "    dplyr::select(dplyr::all_of(names(empty)), dplyr::everything())",
  "",
  "  df",
  "}",
  "",
  "",
  "# ============================================================",
  "# 4) CHARGER LE REGISTRE",
  "# ============================================================",
  "",
  "load_registry <- function() {",
  "",
  "  empty <- normalize_registry_types(tibble::tibble())",
  "",
  "  if (!file.exists(REGISTRY_FP)) {",
  "    return(empty)",
  "  }",
  "",
  "  reg <- tryCatch(",
  "    readr::read_csv(",
  "      REGISTRY_FP,",
  "      col_types = readr::cols(",
  "        sitrep_no    = readr::col_integer(),",
  "        pdf_url      = readr::col_character(),",
  "        date_raw     = readr::col_character(),",
  "        link_text    = readr::col_character(),",
  "        year_in_url  = readr::col_integer(),",
  "        source_page  = readr::col_character(),",
  "        epidemic     = readr::col_character(),",
  "        scraped_at   = readr::col_character(),",
  "        downloaded   = readr::col_logical(),",
  "        extracted    = readr::col_logical(),",
  "        analysed     = readr::col_logical(),",
  "        local_pdf    = readr::col_character(),",
  "        first_seen   = readr::col_character(),",
  "        last_updated = readr::col_character(),",
  "        .default     = readr::col_character()",
  "      ),",
  "      show_col_types = FALSE",
  "    ),",
  "    error = function(e) {",
  "      cat(\"   WARNING: registry could not be read cleanly:\", conditionMessage(e), \"\\n\")",
  "      tibble::tibble()",
  "    }",
  "  )",
  "",
  "  reg <- normalize_registry_types(reg)",
  "",
  "  if (nrow(reg) > 0) {",
  "",
  "    fallback_source <- dplyr::case_when(",
  "      !is.na(reg$pdf_url) & reg$pdf_url != \"\" ~ reg$pdf_url,",
  "      !is.na(reg$source_page) & reg$source_page != \"\" ~ reg$source_page,",
  "      TRUE ~ NA_character_",
  "    )",
  "",
  "    reg$sitrep_no <- purrr::map_int(fallback_source, extract_sitrep_no)",
  "",
  "    reg <- reg %>%",
  "      dplyr::filter(!is.na(sitrep_no), sitrep_no >= 1) %>%",
  "      dplyr::arrange(dplyr::desc(sitrep_no))",
  "  }",
  "",
  "  reg",
  "}",
  "",
  "",
  "# ============================================================",
  "# 5) SAUVEGARDER LE REGISTRE",
  "# ============================================================",
  "",
  "save_registry <- function(registry) {",
  "",
  "  registry <- normalize_registry_types(registry)",
  "",
  "  readr::write_csv(",
  "    registry,",
  "    REGISTRY_FP,",
  "    na = \"\"",
  "  )",
  "}",
  "",
  "",
  "# ============================================================",
  "# 6) FUSIONNER SCRAPING + REGISTRE EXISTANT",
  "# ============================================================",
  "",
  "merge_registry <- function(scraped, registry) {",
  "",
  "  now <- as.character(Sys.time())",
  "",
  "  registry <- normalize_registry_types(registry)",
  "",
  "  scraped <- scraped %>%",
  "    dplyr::mutate(",
  "      sitrep_no    = suppressWarnings(as.integer(sitrep_no)),",
  "      year_in_url  = suppressWarnings(as.integer(year_in_url)),",
  "      pdf_url      = as.character(pdf_url),",
  "      date_raw     = as.character(date_raw),",
  "      link_text    = as.character(link_text),",
  "      source_page  = as.character(source_page),",
  "      epidemic     = as.character(epidemic),",
  "      scraped_at   = as.character(scraped_at),",
  "      downloaded   = FALSE,",
  "      extracted    = FALSE,",
  "      analysed     = FALSE,",
  "      local_pdf    = NA_character_,",
  "      first_seen   = now,",
  "      last_updated = now",
  "    ) %>%",
  "    normalize_registry_types()",
  "",
  "  known_urls <- registry$pdf_url",
  "",
  "  new_rows <- scraped %>%",
  "    dplyr::filter(!pdf_url %in% known_urls) %>%",
  "    normalize_registry_types()",
  "",
  "  pending <- registry %>%",
  "    dplyr::filter(",
  "      pdf_url %in% scraped$pdf_url,",
  "      is.na(downloaded) | downloaded == FALSE |",
  "        is.na(extracted) | extracted == FALSE",
  "    ) %>%",
  "    dplyr::mutate(last_updated = now) %>%",
  "    normalize_registry_types()",
  "",
  "  cat(\"   New SitReps detected:\", nrow(new_rows), \"\\n\")",
  "",
  "  if (nrow(pending) > 0) {",
  "    cat(\"   Pending incomplete:\", nrow(pending), \"\\n\")",
  "  }",
  "",
  "  merged <- dplyr::bind_rows(",
  "    normalize_registry_types(registry),",
  "    normalize_registry_types(new_rows)",
  "  ) %>%",
  "    normalize_registry_types() %>%",
  "    dplyr::distinct(pdf_url, .keep_all = TRUE) %>%",
  "    dplyr::arrange(dplyr::desc(sitrep_no))",
  "",
  "  new_or_pending <- dplyr::bind_rows(",
  "    normalize_registry_types(new_rows),",
  "    normalize_registry_types(pending)",
  "  ) %>%",
  "    normalize_registry_types() %>%",
  "    dplyr::distinct(pdf_url, .keep_all = TRUE) %>%",
  "    dplyr::arrange(dplyr::desc(sitrep_no))",
  "",
  "  list(",
  "    registry       = merged,",
  "    new_or_pending = new_or_pending",
  "  )",
  "}"
)

write_ok <- tryCatch({
  writeLines(enc2utf8(NEW_LINES), con = TARGET_FILE, useBytes = TRUE)
  TRUE
}, error = function(e) {
  cat("WRITE ERROR:", conditionMessage(e), "\n")
  FALSE
})

if (!isTRUE(write_ok)) {
  if (!is.na(BACKUP_FILE) && file.exists(BACKUP_FILE)) {
    file.copy(BACKUP_FILE, TARGET_FILE, overwrite = TRUE)
    cat("Old file restored from backup:", BACKUP_FILE, "\n")
  }
  stop("Replacement failed during writing.")
}

parse_ok <- tryCatch({
  parse(file = TARGET_FILE, encoding = "UTF-8")
  TRUE
}, error = function(e) {
  cat("PARSE ERROR:", conditionMessage(e), "\n")
  FALSE
})

if (!isTRUE(parse_ok)) {
  if (!is.na(BACKUP_FILE) && file.exists(BACKUP_FILE)) {
    file.copy(BACKUP_FILE, TARGET_FILE, overwrite = TRUE)
    cat("Old file restored from backup:", BACKUP_FILE, "\n")
  }
  stop("Replacement failed. The old file was restored.")
}

cat("\n============================================================\n")
cat("PATCH OK — scripts/02_scrape_insp.R replaced and syntax checked.\n")
cat("Now run:\n")
cat('source("D:/PREIS_Ebola_DRC_Sitrep_FV_12.06.26/00_RUN_ALL_PRODUCTION.R")\n')
cat("============================================================\n")
