############################################################
# 05_send_africacdc_sitrep_email.R
#
# Envoie le document Africa CDC (outputs/rapports/PREIS_AfricaCDC_
# SitRep_<NNN>_FINAL.docx, genere par 06_generate_africa_cdc_
# sitrep_final.R) dans un e-mail SEPARE de preis_email_enrichi.R.
#
# POURQUOI UN EMAIL SEPARE (decision explicite du 2026-07-29) :
# preis_email_enrichi.R documente une securite deliberee -- "aucun
# graphique ni carte joints, PDF officiel uniquement". Ce script ne
# touche pas a cette securite : il cree un canal independant plutot
# que de la contourner.
#
# Contenu : un court message (anglais, car les destinataires sont
# chez Africa CDC) + le .docx en piece jointe. Aucune donnee n'est
# recalculee ici -- ce script ne fait qu'attacher et envoyer le
# fichier deja genere.
#
# Anti-doublon : data/preis_africacdc_email_state.csv (meme
# principe que preis_email_enrichi_state.csv, fichier separe pour
# ne pas interferer avec l'autre email).
#
# Usage interactif :
#   source("scripts/05_send_africacdc_sitrep_email.R")
#   send_africacdc_sitrep_email(force = TRUE)
############################################################

.aw_env_get <- function(names, default = "") {
  for (n in names) {
    v <- Sys.getenv(n, "")
    if (nzchar(v)) return(v)
  }
  default
}

send_africacdc_sitrep_email <- function(root = NULL, force = FALSE) {
  old_wd <- getwd()
  on.exit(setwd(old_wd), add = TRUE)

  if (is.null(root)) {
    root <- if (file.exists(file.path(
      getwd(), "outputs", "analyse", "serie_temporelle_nationale.csv"
    ))) {
      getwd()
    } else {
      Sys.getenv("PREIS_BASE_DIR", "D:/PREIS_Ebola_DRC_Sitrep_FV_12.06.26")
    }
  }

  if (!dir.exists(root)) {
    cat("Dossier racine introuvable :", root, "\n")
    return(invisible(FALSE))
  }

  setwd(root)

  suppressPackageStartupMessages({
    library(readr); library(jsonlite)
  })

  registry_fp <- "data/final/sitrep_registry.csv"
  rapports_dir <- "outputs/rapports"
  state_fp <- "data/preis_africacdc_email_state.csv"

  if (!file.exists(registry_fp)) {
    cat("Registre introuvable :", registry_fp, "\n")
    return(invisible(FALSE))
  }

  reg <- tryCatch(readr::read_csv(registry_fp, show_col_types = FALSE), error = function(e) NULL)
  if (is.null(reg) || !"sitrep_no" %in% names(reg) || nrow(reg) == 0) {
    cat("Registre invalide ou vide.\n")
    return(invisible(FALSE))
  }

  sno <- max(suppressWarnings(as.integer(reg$sitrep_no)), na.rm = TRUE)
  if (!is.finite(sno)) {
    cat("Aucun SitRep valide dans le registre.\n")
    return(invisible(FALSE))
  }

  docx_fp <- file.path(rapports_dir, sprintf("PREIS_AfricaCDC_SitRep_%03d_FINAL.docx", sno))

  if (!file.exists(docx_fp)) {
    cat(
      "Document Africa CDC introuvable pour SitRep", sno, ":", docx_fp, "\n",
      "-> lance d'abord scripts/06_generate_africa_cdc_sitrep_final.R\n"
    )
    return(invisible(FALSE))
  }

  # ---- Anti-doublon --------------------------------------------------
  state <- if (file.exists(state_fp)) {
    tryCatch(readr::read_csv(state_fp, show_col_types = FALSE), error = function(e) NULL)
  } else NULL

  already <- !is.null(state) && "sitrep_no" %in% names(state) &&
    sno %in% suppressWarnings(as.integer(state$sitrep_no))

  if (already && !isTRUE(force)) {
    cat("SitRep", sno, "deja notifie (Africa CDC docx). Aucun nouvel envoi.\n")
    return(invisible(TRUE))
  }

  # ---- Corps du message (anglais -- destinataires Africa CDC) --------
  subject <- sprintf(
    "PREIS Africa CDC Supplement - SitRep No.%03d (DRC quantitative summary)",
    sno
  )

  html <- paste0(
    "<div style='font-family:Segoe UI,Arial,sans-serif;color:#252525;max-width:640px;line-height:1.5'>",
    "<div style='background:#1A5632;color:#fff;padding:16px 20px;border-radius:8px'>",
    "<div style='font-size:17px;font-weight:700'>PREIS &mdash; Africa CDC SitRep Supplement</div>",
    "<div style='font-size:13px;margin-top:3px'>SitRep No. ", sprintf("%03d", sno), "</div>",
    "</div>",
    "<p style='margin-top:16px'>Please find attached the DRC quantitative supplement for SitRep No. ",
    sprintf("%03d", sno),
    ", automatically generated by PREIS in the Africa CDC EIU template ",
    "(national/provincial/health-zone indicators, epidemic curve, operational watch).</p>",
    "<p style='font-size:12px;color:#666'>",
    "This document covers DRC quantitative indicators only. It does not include Uganda data ",
    "or Africa CDC operational/coordination updates, which are compiled separately by the EIU team. ",
    "Sections requiring field verification are clearly labelled as such in the document.",
    "</p>",
    "</div>"
  )

  plain <- sprintf(
    "PREIS Africa CDC Supplement - SitRep No.%03d. See attached document (DRC quantitative indicators only).",
    sno
  )

  # ---- SMTP (memes identifiants que preis_email_enrichi.R) -----------
  smtp_user <- .aw_env_get(c("SMTP_USER", "SMTP_USERNAME"))
  smtp_pass <- .aw_env_get(c("SMTP_PASS", "SMTP_PASSWORD"))
  from <- .aw_env_get(c("ALERT_FROM", "EMAIL_FROM", "SMTP_FROM", "MAIL_FROM"), smtp_user)

  # Liste de destinataires DEDIEE (peut differer de l'email officiel) --
  # si PREIS_AFRICACDC_TO n'est pas defini, retombe sur la meme liste
  # que l'email enrichi pour ne pas bloquer le premier envoi.
  to <- .aw_env_get(
    c("PREIS_AFRICACDC_TO", "ALERT_TO", "EMAIL_TO", "PREIS_ALERT_TO", "PREIS_EMAIL_TO", "SMTP_TO", "MAIL_TO"),
    from
  )

  if (!nzchar(smtp_user) || !nzchar(smtp_pass)) {
    cat("Identifiants SMTP manquants (SMTP_USER / SMTP_PASS).\n")
    return(invisible(FALSE))
  }
  if (!nzchar(from) || !nzchar(to)) {
    cat("Expediteur ou destinataires manquants.\n")
    return(invisible(FALSE))
  }

  to_vec <- unique(trimws(unlist(strsplit(to, "[,;]"))))
  to_vec <- to_vec[nzchar(to_vec)]
  if (length(to_vec) == 0) {
    cat("Liste des destinataires vide.\n")
    return(invisible(FALSE))
  }

  cfg_dir <- file.path(tempdir(), "preis_africacdc_email")
  dir.create(cfg_dir, recursive = TRUE, showWarnings = FALSE)

  cfg <- list(
    from = from, to = as.list(to_vec), subject = subject,
    html = html, plain = plain, attachments = list(docx_fp)
  )
  cfg_fp <- file.path(cfg_dir, "cfg.json")
  writeLines(jsonlite::toJSON(cfg, auto_unbox = TRUE), cfg_fp, useBytes = TRUE)

  py <- c(
    "import sys, json, os, ssl, smtplib",
    "from email.message import EmailMessage",
    "from pathlib import Path",
    "cfg = json.load(open(sys.argv[1], encoding='utf-8'))",
    "host = os.environ.get('SMTP_HOST') or 'smtp.gmail.com'",
    "port = int(os.environ.get('SMTP_PORT') or '465')",
    "user = os.environ.get('SMTP_USER') or os.environ.get('SMTP_USERNAME') or ''",
    "pw = os.environ.get('SMTP_PASS') or os.environ.get('SMTP_PASSWORD') or ''",
    "use_ssl = (str(os.environ.get('SMTP_SSL','')).lower() in ('1','true','yes')) or port == 465",
    "msg = EmailMessage()",
    "msg['From'] = cfg['from']",
    "msg['To'] = ', '.join(cfg['to'])",
    "msg['Subject'] = cfg['subject']",
    "msg.set_content(cfg.get('plain', 'See attached document.'))",
    "msg.add_alternative(cfg['html'], subtype='html')",
    "for a in cfg.get('attachments', []):",
    "    p = Path(a)",
    "    if p.is_file():",
    "        ext = p.suffix.lower()",
    "        if ext == '.docx':",
    "            mt, st = 'application', 'vnd.openxmlformats-officedocument.wordprocessingml.document'",
    "        else:",
    "            mt, st = 'application', 'octet-stream'",
    "        msg.add_attachment(p.read_bytes(), maintype=mt, subtype=st, filename=p.name)",
    "ctx = ssl.create_default_context()",
    "if use_ssl:",
    "    with smtplib.SMTP_SSL(host, port, timeout=120, context=ctx) as s:",
    "        s.login(user, pw)",
    "        s.send_message(msg)",
    "else:",
    "    with smtplib.SMTP(host, port, timeout=120) as s:",
    "        s.ehlo(); s.starttls(context=ctx); s.ehlo()",
    "        s.login(user, pw)",
    "        s.send_message(msg)",
    "print('SENT_OK')"
  )
  py_fp <- file.path(cfg_dir, "send.py")
  writeLines(py, py_fp, useBytes = TRUE)

  py_bin <- Sys.which("python3")
  if (!nzchar(py_bin)) py_bin <- Sys.which("python")
  if (!nzchar(py_bin)) {
    cat("Python introuvable.\n")
    return(invisible(FALSE))
  }

  out <- tryCatch(
    system2(py_bin, c(shQuote(py_fp), shQuote(cfg_fp)), stdout = TRUE, stderr = TRUE),
    error = function(e) conditionMessage(e)
  )
  cat(paste(out, collapse = "\n"), "\n")

  if (!any(grepl("SENT_OK", out, fixed = TRUE))) {
    cat("Echec de l'envoi de l'e-mail Africa CDC.\n")
    return(invisible(FALSE))
  }

  new_row <- data.frame(
    sitrep_no = sno,
    sent_utc = format(Sys.time(), "%Y-%m-%d %H:%M:%S UTC", tz = "UTC"),
    stringsAsFactors = FALSE
  )
  if (is.null(state) || !all(names(new_row) %in% names(state))) {
    state2 <- new_row
  } else {
    state$sitrep_no <- suppressWarnings(as.integer(state$sitrep_no))
    state <- state[state$sitrep_no != sno | is.na(state$sitrep_no), names(new_row), drop = FALSE]
    state2 <- rbind(state, new_row)
  }
  tryCatch(readr::write_csv(state2, state_fp),
           error = function(e) cat("Avertissement : etat anti-doublon non enregistre.\n"))

  cat("\nE-mail Africa CDC ENVOYE pour SitRep", sno, "->", paste(to_vec, collapse = ", "), "\n")
  cat("Piece jointe :", basename(docx_fp), "\n")
  invisible(TRUE)
}

if (!interactive()) {
  ok <- send_africacdc_sitrep_email(
    force = isTRUE(as.logical(Sys.getenv("PREIS_FORCE_SEND", "FALSE")))
  )
  if (!isTRUE(ok)) quit(save = "no", status = 2)
}
